name = "dhyaanshilaa-backend"
type = "javascript"
account_id = "ff9fa638c37d031511def7dc3e2be1a9"
workers_dev = true
main = "./dist/server.js"
compatibility_date = "2024-03-03"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"



